- block:

  - import_tasks: tasks/deploy-zfs-repo.yml
    when: deployzfs_stage|default("one") == "one"

  - import_tasks: tasks/deploy-zfs-stage-1.yml
    when: deployzfs_stage|default("one") == "one"

  - import_tasks: tasks/deploy-zfs-stage-2.yml
    when: deployzfs_stage|default("two") == "two"

  when: ansible_distribution in "Fedora Qubes"
  tags:
  - zfs
