xmpp:
  # Use this variable to add JIDs (accounts) to your server.
  # Note that the password set here is only the initial password.
  # Example:
  # jids:
  #   user@example.com: passwordinplaintext
  jids: {}
  global_stanzas:
    http_max_content_size: 104857600
    http_upload_file_size_limit: 104857600
  modules_origin:
    source: https://hg.prosody.im/prosody-modules/
    revision: 81956bb99289
  modules:
  # Generally required
  - roster      # ; -- Allow users to have a roster. Recommended ;)
  - saslauth    # ; -- Authentication for clients and servers. Recommended if you want to log in.
  - tls         # ; -- Add support for secure TLS on c2s/s2s connections
  - dialback    # ; -- s2s dialback support
  - disco       # ; -- Service discovery
  # Not essential, but recommended
  - private     # ; -- Private XML storage (for room bookmarks, etc.)
  - vcard       # ; -- Allow users to set vCards
  # Nice to have
  - version     # ; -- Replies to server version requests
  - uptime      # ; -- Report how long server has been running
  - time        # ; -- Let others know the time here on this server
  - ping        # ; -- Replies to XMPP pings with pongs
  - pep         # ; -- Enables users to publish their mood, activity, playing music and more
  - register    # ; -- Allow users to register on this server using a client and change passwords
  # compliance with Conversations as per https://github.com/siacs/Conversations
  - proxy65
  - smacks
  - smacks_offline
  - carbons
  - mam
  - csi
  - filter_chatstates
  - throttle_presence
  - http_upload
  - cloud_notify
  extra_modules: []
  logging:
    # Logging to /var/log/prosody/prosody.log can be info or debug.
    prosody_log: info
    # Logging to syslog can be info or debug.
    syslog: info
# Use the following variables to set up the certificates for your server.
# An example follows:
# ssl:
#   example.com:
#     key:           /etc/pki/tls/private/example.com.key
#     user_may_read: prosody
#     intermediates:
#     # The order matters.  At the bottom of the stack must be the one closest to the root of trust.
#     - /etc/pki/tls/certs/example_com.ca-bundle
#     certificate:   /etc/pki/tls/certs/example_com.crt
#     assembled:     /etc/pki/tls/certs/assembled_example.com.crt
ssl: {}
