- name: symlink sieve plugins
  shell: |
    set -ex
    cd /usr/lib64/dovecot/sieve
    for plugin in *.so ; do
      test -f "../$plugin" && continue || true
      ln -s "sieve/$plugin" ../"$plugin"
      echo CHANGED
    done
  register: sieve_symlinks
  changed_when: '{{ "CHANGED" in sieve_symlinks.stdout }}'
  tags:
  - dovecotplugins

- name: install dovecot configuration files
  template: src=templates/dovecot{{ item }} dest={{ item }} mode=0644 owner=root group=root
  with_items:
  - /etc/dovecot/local.conf
  register: dovecot_config
  tags: doveconf

- name: create dovecot sieve global directories
  file: name={{ item }} state=directory owner=root group=root mode=0755 setype=dovecot_etc_t seuser=system_u
  with_items:
  - /var/lib/sieve
  - /var/lib/sieve/before.d
  - /var/lib/sieve/after.d
  - /var/lib/sieve/global
  - /var/lib/sieve/imapsieve
  tags: sieve

- name: create dovecot sieve directory for programs to be used with pipe and filter
  file: name={{ item }} state=directory owner=root group=root mode=0755
  with_items:
  - /usr/local/libexec/sieve
  tags: sieve

- name: deploy dovecot global scripts
  copy:
    src: files/dovecot/var/lib/sieve/{{ item }}/
    dest: /var/lib/sieve/{{ item }}/
    owner: root
    group: root
    mode: 0644
    setype: dovecot_etc_t
    seuser: system_u
  with_items:
  - before.d
  - after.d
  - global
  - imapsieve
  register: sieve_global
  tags: sieve

- name: compile dovecot global scripts
  shell: |
    set -e
    for item in before.d after.d global imapsieve ; do
      cd /var/lib/sieve/$item
      for script in *.sieve ; do
        if ! test -f "$script" ; then continue ; fi
        compiled=$(echo "$script" | sed 's/.sieve$/.svbin/')
        agescript=`stat -c "%Y" "$script"`
        agecompiled=`stat -c "%Y" "$compiled" || echo 0`
        if [ "$agescript" -gt "$agecompiled" ] ; then
            sievec -x '+vnd.dovecot.pipe +vnd.dovecot.execute +vnd.dovecot.filter' "$script"
            chcon -u system_u -t dovecot_etc_t "$compiled"
            echo CHANGED recompiled "$script"
        fi
      done
      for compiled in *.svbin ; do
        if ! test -f "$compiled" ; then continue ; fi
        if ! test -f $(echo "$compiled" | sed 's/.svbin$/.sieve/') ; then
          rm -f "$compiled"
          echo CHANGED deleted "$compiled"
        fi
      done
    done
  register: sieve_global_compile
  changed_when: '{{ "CHANGED" in sieve_global_compile.stdout }}'
  tags:
  - sieve
  - sievec

- name: install ham / spam classifier
  template: src=templates/dovecot/usr/local/libexec/sieve/spamclassifier dest=/usr/local/libexec/sieve/spamclassifier mode=0755 owner=root group=root
  tags:
  - sieve
  - classifiers

- name: install ham / spam reclassifiers
  template: src=templates/dovecot/usr/local/libexec/sieve/learn dest=/usr/local/libexec/sieve/learn-{{ item }} mode=0755 owner=root group=root
  with_items:
  - ham
  - spam
  tags:
  - sieve
  - classifiers
