- include: packages.yml
  tags:
  - packages
  - dovecot
  - postfix
  - spf
  - dkim

- import_tasks: postgrey.yml
  tags:
  - postgrey

- import_role:
    name: deploy-ssl-certs
  tags: ssl

- import_tasks: spf.yml
  tags:
  - spf

- import_tasks: dkim.yml
  tags:
  - dkim

- import_tasks: dovecot.yml
  tags:
  - dovecot

- import_tasks: postfix.yml
  tags:
  - postfix

- import_tasks: accounts.yml
  tags:
  - accounts

- import_tasks: services.yml

- import_tasks: test.yml
  tags:
  - test
