# This is now fully mirrored in the email.mta SaltStack formula.

- name: install required software
  package: name={{ item }} state=present
  with_items:
  - postgrey
  - postfix
  - mailx
  - bogofilter
  - dovecot
  - dovecot-pigeonhole
  - ca-certificates
  - pypolicyd-spf
  - opendkim
- name: remove sendmail
  package: name=sendmail state=absent
