# This is now fully mirrored in the email.mta SaltStack formula.

- name: install required software
  package: name={{ item }} state=present
  with_items:
  - postgrey # ported
  - postfix # ported
  - mailx # no need to port
  - bogofilter
  - dovecot # ported
  - dovecot-pigeonhole
  - ca-certificates # ported
  - pypolicyd-spf # ported
  - opendkim # ported
- name: remove sendmail # not to port
  package: name=sendmail state=absent
