- name: enable postgrey local SELinux module
  include_role:
    name: selinux-module
  vars:
    policy_file: files/postgrey/postgreylocal.te
    state: enabled
  tags:
  - selinux
  when: spam.greylisting

- name: enable postgrey
  service: name=postgrey enabled={{ spam.greylisting }} state={% if spam.greylisting %}started{% else %}stopped{% endif %}
