- name: enable postfix
  service:
    name: postfix
    enabled: yes
    state: '{% if postfix_config.changed|default(False) or (sslconf is defined and sslconf.changed) %}re{% endif %}started'
  tags: postfix

- name: enable opendkim
  service:
    name: opendkim
    enabled: yes
    state: '{% if dkim_config.changed|default(False) or dkim_privkeys.changed|default(False) %}re{% endif %}started'
  tags: dkim

- name: enable dovecot
  service:
    name: dovecot
    enabled: yes
    state: '{% if dovecot_config.changed|default(False) or (sslconf is defined and sslconf.changed) %}re{% endif %}started'
  tags: dovecot
