- block:
  - name: detect GRUB configuration
    shell: for f in /boot/efi/EFI/{{ ansible_distribution|lower }}/grub.cfg /boot/grub/grub.cfg /boot/grub2/grub.cfg ; do test -f "$f" && { echo "$f" ; exit ; } ; done
    register: grubcfgfile
    check_mode: no
    changed_when: False
  - name: regenerate GRUB configuration
    shell: /usr/sbin/grub{% if ansible_distribution in "Fedora Qubes" %}2{% endif %}-mkconfig -o {{ grubcfgfile.stdout_lines[0] }}
  - name: set default to 0
    shell: /usr/sbin/grub{% if ansible_distribution in "Fedora Qubes" %}2{% endif %}-set-default 0
  tags:
  - grub
