- name: regenerate GRUB configuration
  shell: |
        if [ -f /usr/sbin/grub{% if ansible_distribution in "Fedora Qubes" %}2{% endif %}-mkconfig ] ; then
          if [ -f /etc/grub{% if ansible_distribution in "Fedora Qubes" %}2{% endif %}-efi.cfg ] ; then
            GRUB_VERSION=2
            GRUB_MENU_LST=/etc/grub{% if ansible_distribution in "Fedora Qubes" %}2{% endif %}-efi.cfg
            GRUB_MKCONFIG=/usr/sbin/grub{% if ansible_distribution in "Fedora Qubes" %}2{% endif %}-mkconfig
          elif [ -f /etc/grub{% if ansible_distribution in "Fedora Qubes" %}2{% endif %}.cfg ] ; then
            GRUB_VERSION=2
            GRUB_MENU_LST=/etc/grub{% if ansible_distribution in "Fedora Qubes" %}2{% endif %}.cfg
            GRUB_MKCONFIG=/usr/sbin/grub{% if ansible_distribution in "Fedora Qubes" %}2{% endif %}-mkconfig
          fi
        elif [ -f /usr/sbin/grubby -a -f /boot/grub/grub.conf ] ; then
          GRUB_VERSION=1
          GRUB_MENU_LST=/boot/grub/grub.conf
          GRUB_MKCONFIG/bin/true
        fi
        GRUB_SET_DEFAULT=/usr/sbin/grub{% if ansible_distribution in "Fedora Qubes" %}2{% endif %}-set-default
        {% if ansible_check_mode %}echo {% endif %}$GRUB_MKCONFIG -o $GRUB_MENU_LST || exit $?
        test -f /usr/sbin/grubby && {% if ansible_check_mode %}echo {% endif %}/usr/sbin/grubby --set-default-index=0 || {% if ansible_check_mode %}echo {% endif %}$GRUB_SET_DEFAULT 0
  check_mode: no
  when: qubes is not defined or qubes.vm_type is not defined
  tags:
  - grub
