- block:
    - name: Detect GRUB version
      shell: |
        if [ -f /usr/sbin/grub{% if ansible_distribution in "Fedora Qubes" %}2{% endif %}-mkconfig ] ; then
        if [ -f /etc/grub{% if ansible_distribution in "Fedora Qubes" %}2{% endif %}-efi.cfg ] ; then
            echo 2
            echo /etc/grub{% if ansible_distribution in "Fedora Qubes" %}2{% endif %}-efi.cfg
            echo /usr/sbin/grub{% if ansible_distribution in "Fedora Qubes" %}2{% endif %}-mkconfig
        if [ -f /etc/grub{% if ansible_distribution in "Fedora Qubes" %}2{% endif %}.cfg ] ; then
            echo 2
            echo /etc/grub{% if ansible_distribution in "Fedora Qubes" %}2{% endif %}.cfg
            echo /usr/sbin/grub{% if ansible_distribution in "Fedora Qubes" %}2{% endif %}-mkconfig
        fi
        fi
        if [ -f /usr/sbin/grubby -a -f /boot/grub/grub.conf ] ; then
        echo 1
        echo /boot/grub/grub.conf
        echo /bin/true
        fi
      register: _grub
      check_mode: no
      changed_when: False

    - name: set GRUB variables
      set_fact:
        grub_version: _grub.stdout_lines[0]
        grub_menu_lst: _grub.stdout_lines[1]
        grub_mkconfig: _grub.stdout_lines[2]
      check_mode: no

    - name: regenerate GRUB configuration
      shell: '{{ grub_mkconfig }} -o {{ grub_menu_lst }}'
  tags:
  - grub
