---

- name: redo initramfs
  shell: |
      set -e
      cd /boot
      kvers=
      for kver in initramfs-*.img initramfs-*.img.knowngood /lib/modules/* ; do
          kver=$(basename "$kver")
          kver=${kver#initramfs-}
          kver=${kver%.knowngood}
          kver=${kver%.img}
          if echo "$kvers" | grep -q "$kver" ; then
              true
          else
              kvers="$kvers $kver"
          fi
      done
      set -x
      for kver in $kvers ; do
          libmodules=/lib/modules/"$kver"
          initramfs=initramfs-$kver.img
          knowngood=$initramfs.knowngood
          vmlinuz=vmlinuz-$kver
          if [ ! -e "$libmodules" ] ; then
              echo "$libmodules does not exist, continuing" >&2
              continue
          fi
          if [ ! -f "$vmlinuz" ] ; then
              echo "$vmlinuz does not exist, removing obsolete initramfs and /lib/modules" >&2
              rm -fr "$initramfs" "$initramfs.knowngood" /lib/modules/"$ver"
              echo CHANGED removed obsolete files
              continue
          fi
          if [ ! -f "$knowngood" ] ; then
              cp -f "$initramfs" "$knowngood" && echo CHANGED backup made of "$initramfs"
          fi
      done
      dracut -f --regenerate-all && echo CHANGED regenerated all initial RAM disks
  register: regenramfs
  when: ansible_distribution in "Fedora Qubes"
  changed_when: "'CHANGED' in regenramfs.stdout"
