---

- name: redo initramfs
  shell: |
      set -ex
      cd /boot
      for initramfs in initramfs-*.img initramfs-*.img.knowngood /lib/modules/* ; do
          if [ ! -e "$initramfs" ] ; then continue ; fi
          initramfs=$(basename "$initramfs")
          vmlinuz=vmlinuz-${initramfs#initramfs-}
          vmlinuz=${vmlinuz%.knowngood}
          vmlinuz=${vmlinuz%.img}
          initramfs=${initramfs%.knowngood}
          initramfs=${initramfs%.knowngood}
          ver=${vmlinuz#vmlinuz-}
          if [ ! -f "$vmlinuz" ] ; then
              echo "$vmlinuz does not exist, removing obsolete initramfs and /lib/modules" >&2
              rm -fr "$initramfs" "$initramfs.knowngood" /lib/modules/"$ver"
              echo CHANGED
              continue
          fi
          if [ ! -f "$initramfs".knowngood ] ; then
              cp -f "$initramfs" "$initramfs".knowngood && echo CHANGED backup made of "$initramfs"
          fi
      done
      dracut -f --regenerate-all && echo CHANGED regenerated all initial RAM disks
  register: regenramfs
  when: ansible_distribution in "Fedora Qubes"
  changed_when: "'CHANGED' in regenramfs.stdout"
