---
- name: test that boot is mounted, abort otherwise
  shell: |
    for mntpnt in /boot /boot/efi ; do
      if grep -q $mntpnt /etc/fstab
      then
        if ! mountpoint $mntpnt
        then
          mount $mntpnt
          sleep 1
          mountpoint $mntpnt || {
            # Oh shit the mount unit is actually associated with a device unit
            # whose /sys path is obsolete.  Tell systemd to reload the units.
            systemctl --system daemon-reload
            mount $mntpnt
            mountpoint $mntpnt || exit 4
          }
          echo CHANGED
        fi
      else
        true
      fi
    done
  register: testboot
  changed_when: testboot.stdout.find("CHANGED") != -1
  notify: unmount boot
  tags:
  - zfs
  - grub
