- name: reread variables
  action: setup

- include_role:
    name: updates

- name: remove distrover file
  file: name=/.distupgrade state=absent

- name: disable debug shell
  service: name=debug-shell state=stopped enabled=no
  when: debug_shell
