- include: testboot.yml

- include: variables.yml
  when: ansible_distribution in "Fedora Qubes Debian Ubuntu"
  tags:
  - after

- include: prepare.yml
  when: ansible_distribution in "Fedora Qubes Debian Ubuntu"

- include: upgrade.yml
  when: ansible_distribution in "Fedora Qubes Debian Ubuntu" and targetdistrover|int != ansible_distribution_version|int

- include: cleanup.yml
  when: ansible_distribution in "Fedora Qubes Debian Ubuntu"
  tags:
  - after
