- include: testboot.yml

- include: variables.yml
  when: '{{ ansible_distribution in "Fedora Qubes" }}'
  tags:
  - after

- include: prepare.yml
  when: '{{ ansible_distribution in "Fedora Qubes" }}'

- include: upgrade.yml
  when: '{{ ansible_distribution in "Fedora Qubes" }}'

- include: cleanup.yml
  when: '{{ ansible_distribution in "Fedora Qubes" }}'
  tags:
  - after
