- name: record source distribution version upgrade and request relabeling if needed
  shell: |
      set -e
      created=
      if ! test -f /.distupgrade ; then
        created=true
        echo CHANGED >> /dev/stderr
        echo {{ ansible_distribution_version|int }} > /.distupgrade
        echo {{ ansible_distribution_version|int + 1 }} >> /.distupgrade
        {% if ansible_check_mode|default(False) %}selinuxenabled && touch /.autorelabel || true{% endif %}

      fi
      cat /.distupgrade

      {% if ansible_check_mode|default(False) %}test -n "$created" && rm -f /.distupgrade || true{% endif %}
  register: distrovercontent
  check_mode: no
  changed_when: '"CHANGED" in distrovercontent.stderr'

- name: record if there is a kernel package
  shell: |
    {% if ansible_distribution in "Fedora Qubes" %}
    rpm -qa | grep -q '^kernel-[0123456789]' && echo YES || echo NO
    {% elif ansible_distribution in "Debian Ubuntu" %}
    dpkg -l | grep -q linux-kernel && echo YES || echo NO
    {% endif %}
  check_mode: no
  register: kernelpkgcontent
  changed_when: False

- name: set variables up
  set_fact:
    distrover: '{{ distrovercontent.stdout_lines[0] }}'
    targetdistrover: '{{ distrovercontent.stdout_lines[1] }}'
    kernelpkgavailable: '{{ "YES" in kernelpkgcontent.stdout }}'
    base_packages: fedora-release dnf systemd

- name: set debug_shell / method to dnf-upgrade / system-upgrade / distro-sync / qubes-dom0-update
  set_fact:
    debug_shell: '{% if (ansible_distribution in "Fedora" and distrover|int >= 23)
                        or (ansible_distribution in "Debian Ubuntu") %}yes{% else %}no{% endif %}'
    method: '{% if ansible_distribution in "Fedora"
               and distrover|int == 22
             %}dnf-upgrade{%
               elif ansible_distribution in "Fedora"
               and distrover|int >= 23
               and (
                   kernelpkgavailable
                   and (qubes.vm_type|default("")) not in ["TemplateVM", "StandaloneVM"]
               )
             %}system-upgrade{%
               elif ansible_distribution in "Fedora"
               and distrover|int >= 23 and (
                   not kernelpkgavailable
                   or (qubes.vm_type|default("")) in ["TemplateVM", "StandaloneVM"]
               )
             %}distro-sync{%
               elif ansible_distribution in "Qubes"
             %}qubes-dom0-update{%
               elif ansible_distribution in "Debian Ubuntu"
             %}dist-upgrade{%
               endif
             %}'

- name: set method to apt-get dist-upgrade
  set_fact:
    debian_distro_map:
      7: wheezy
      8: jessie
      9: stretch
      10: buster
  when: method == "dist-upgrade" 
