---
- include: testboot.yml
  tags:
  - zfs

- name: test for ZFS
  shell: which zfs && echo YES || echo NO
  changed_when: false
  register: zfstest
  check_mode: no
  tags:
  - zfs

- include_role:
    name: zfsupdates
  vars:
    deployzfs_stage: one
  when: '"YES" in zfstest.stdout'

- name: update yum packages for non-qubes dom0s
  package: state=latest name=* enablerepo='qubes-vm-*-security-testing'
  when: ansible_distribution in "Fedora"
  register: do_updates_dnf

- name: update apt packages
  apt: upgrade=yes
  when: ansible_distribution in ("Debian", "Ubuntu")
  register: do_updates_apt

- name: update yum packages for qubes dom0s
  shell: qubes-dom0-update -y --enablerepo=qubes-dom0-security-testing
  when: ansible_distribution in "Qubes"
  register: do_updates_dom0
  failed_when: do_updates_dom0.rc != 0
  changed_when: '"Running transaction" in do_updates_dom0.stdout'

- name: redo akmods
  shell: if test -f /usr/sbin/akmods ; then akmods --force ; fi
  when: '"kmod-nvidia" in "".join((do_updates_dnf.results|default([]) + do_updates_dom0.stdout_lines|default([])))'
  register: redo_akmods

- include_role:
    name: zfsupdates
  vars:
    deployzfs_stage: two
  when: '"YES" in zfstest.stdout'

- name: is this Qubes template VM
  shell: test -f /run/qubes/this-is-templatevm && echo YES || echo NO
  changed_when: False
  check_mode: no
  register: templatevm

- name: clean downloaded yum packages
  shell: test -f /usr/bin/dnf && { dnf clean packages ; } || { yum clean packages ; }
  when: ansible_distribution in "Fedora" and "YES" in templatevm.stdout and (do_updates_dnf.changed|default(False))
  register: clean_updates
  changed_when: "'0 packages removed' not in clean_updates.stdout"

- set_fact:
    update_results: '{{ ((do_updates_apt|default({"results": []})).results|default([])
                       + (do_updates_dnf|default({"results": []})).results|default([])
                       + (do_updates_dom0|default({"stdout_lines": []})).stdout_lines|default([]))|join("\n") }}'
    grub_set_default_zero: yes
  tags:
  - grub

- block:
  - include: grub2-regen.yml
  when: ansible_distribution in "Fedora Qubes Debian Ubuntu" and ("linux-" in update_results or "kernel" in update_results or "xen" in update_results)
  tags:
  - grub
