---
- include: testboot.yml
  tags:
  - zfs

- name: test for ZFS
  shell: which zfs && echo YES || echo NO
  changed_when: false
  register: zfstest
  check_mode: no
  tags:
  - zfs

- include_role:
    name: zfsupdates
  vars:
    deployzfs_stage: one
  when: '"YES" in zfstest.stdout'

- name: update yum packages for non-qubes dom0s
  package: state=latest name=* enablerepo='qubes-vm-*-security-testing'
  when: ansible_distribution in "Fedora"
  register: do_updates_dnf

- name: update apt packages
  apt: upgrade=yes
  when: ansible_distribution in ("Debian", "Ubuntu")
  register: do_updates_apt

- name: update yum packages for qubes dom0s
  shell: qubes-dom0-update -y --enablerepo=qubes-dom0-security-testing
  when: ansible_distribution in "Qubes"
  register: do_updates_dom0
  failed_when: do_updates_dom0.rc != 0
  changed_when: '"Running transaction" in do_updates_dom0.stdout'

- name: redo akmods
  shell: if test -f /usr/sbin/akmods ; then akmods --force ; fi
  when: '"kmod-nvidia" in "".join((do_updates_dnf.results|default([]) + do_updates_dom0.stdout_lines|default([])))'
  register: redo_akmods

- include_role:
    name: zfsupdates
  vars:
    deployzfs_stage: two
  when: '"YES" in zfstest.stdout'

- name: clean downloaded yum packages
  shell: test -f /usr/bin/dnf && { dnf clean packages ; } || { yum clean packages ; }
  when: ansible_distribution in "Fedora" and inventory_hostname in groups["qubes-managed-templates"]|default([]) and (do_updates_dnf.changed|default(False))
  register: clean_updates
  changed_when: "'0 packages removed' not in clean_updates.stdout"

- name: detect grub
  shell: test -f /usr/sbin/grub2-mkconfig && { echo TWO ; exit ; } || test -f /usr/sbin/grubby -a -f /boot/grub/grub.conf && { echo ONE ; } || true
  register: grub
  when: ansible_distribution in "Fedora Qubes" and ("kernel" in "".join((do_updates_dnf.results|default([]) + do_updates_dom0.stdout_lines|default([]))) or "xen" in "".join((do_updates_dnf.results|default([]) + do_updates_dom0.stdout_lines|default([]))) )
  check_mode: no
  changed_when: False
  tags:
  - grub

- include: grub2-regen.yml
  when: '"TWO" in grub.stdout|default("")'

- name: set GRUB1 default
  shell: /usr/sbin/grubby --set-default-index=0
  when: '"ONE" in grub.stdout|default("")'
  tags:
  - grub
