# Conforms to the latest Deployment policies.md in the documentation.

- block:
  - name: create repo file
    copy:
      content: |
        [{{ generic_rpm_install.dnf_repo_name }}]
        name={{ generic_rpm_install.dnf_repo_name }} for $releasever - $basearch
        baseurl={{ generic_rpm_install.dnf_repo_base_url }}/{% if ansible_distribution in "Qubes" %}q{% else %}fc{% endif %}$releasever/
        enabled=1
        gpgcheck={% if generic_rpm_install.gpgcheck %}1{% else %}0{% endif %}

        metadata_expire=30

      dest: /etc/yum.repos.d/{{ generic_rpm_install.dnf_repo_name }}.repo
      mode: 0644
      owner: root
      group: root
    when: generic_rpm_install.configrepo
    register: repofile

  - name: construct callee parameters
    set_fact:
      __generic_rpm_install:
        packages: '{{ [package] }}'
    no_log: yes

  - import_role:
      name: install-packages
    vars:
      state: latest
      packages: '{{ __generic_rpm_install["packages"] }}'

  - set_fact:
      __generic_rpm_install: {}
    no_log: yes

  - set_fact:
      '{{ register_var|default("generic_rpm_install") }}': '{{ package_install }}'
  tags:
  - generic_rpm_install
