# Conforms to the latest Deployment policies.md in the documentation.

- block:
  - name: remove shared directory for packages
    file: name='{{ generic_rpm_install.package_cache_root }}/{{ project }}/packages' state=absent
    when: ansible_distribution in "Fedora Qubes"

  - name: create repo file
    copy:
      content: |
        [{{ generic_rpm_install.dnf_repo_name }}]
        name={{ generic_rpm_install.dnf_repo_name }} for $releasever - $basearch
        baseurl={{ generic_rpm_install.dnf_repo_base_url }}/{% if ansible_distribution in "Qubes" %}q{% else %}fc{% endif %}$releasever/
        enabled=1
        gpgcheck={% if generic_rpm_install.gpgcheck %}1{% else %}0{% endif %}

        metadata_expire=30

      dest: /etc/yum.{% if ansible_distribution in "Qubes" %}real.{% endif %}repos.d/{{ generic_rpm_install.dnf_repo_name }}.repo
      mode: 0644
      owner: root
      group: root
    when: ansible_distribution in "Fedora Qubes" and generic_rpm_install.configrepo
    register: repofile

  - name: delete old repo file
    file: name=/etc/yum.{% if ansible_distribution in "Qubes" %}real.{% endif %}repos.d/{{ project }}.repo state=absent

  - set_fact:
      packages: '{{ [package] }}'
    when: packages is not defined and package is defined

  - import_role:
      name: install-packages
    vars:
      state: latest
    when: packages is defined

  - set_fact:
      '{{ register_var|default("generic_rpm_install") }}': '{{ package_install }}'
    when: ansible_distribution in "Fedora Qubes" and packages is defined
  tags:
  - generic_rpm_install
