- name: install prosody
  package: name=prosody state=present
  tags: package

- name: install prosody modules from package
  import_role:
    name: generic-rpm-install
  vars:
    project: prosody-modules
    package: prosody-modules
    register_var: installprosodymodules
  when: xmpp.modules_origin == "package"
  tags: modules

- name: install prosody modules from Mercurial
  include: modules-from-mercurial.yml
  when: xmpp.modules_origin != "package"
  tags: modules

- include_role:
    name: deploy-ssl-certs
  tags: ssl

# This task will change every time the modules on disk have changed...
- name: scavenge module info
  shell: |
    {% for module in xmpp.modules + xmpp.extra_modules %}
    if test -d /usr/share/prosody-modules/mod_{{ module|quote }}/ ; then
      mod=/usr/share/prosody-modules/mod_{{ module|quote }}/
    elif test -d /usr/lib64/prosody/modules/mod_{{ module|quote }}/ ; then
      mod=/usr/lib64/prosody/modules/mod_{{ module|quote }}/
    else
      mod=/usr/lib64/prosody/modules/mod_{{ module|quote }}.lua
    fi
    ls -l --sort=time "$mod" || {
      echo Module mod_{{ module|quote }} does not exist in /usr/share/prosody-modules or /usr/lib64/prosody/modules >&2
      exit 48
    }
    {% endfor %}
  register: prosodymodulestat
  check_mode: no
  changed_when: False
  tags:
  - modules
  - config

# ...and the side effect of the prior task changing, is that this task will change too.
- name: configure prosody modules and ports
  template:
    src: etc/prosody/{{ item }}.cfg.lua.j2
    dest: /etc/prosody/{{ item }}.cfg.lua
    owner: root
    group: prosody
    mode: 0640
  with_items:
  - modules
  - ports
  register: prosodyconfigrestarts
  tags:
  - modules
  - config

- name: configure prosody
  template:
    src: etc/prosody/prosody.cfg.lua.j2
    dest: /etc/prosody/prosody.cfg.lua
    owner: root
    group: prosody
    mode: 0640
  register: prosodyconfig
  tags: config

- name: enable and start prosody
  service:
    name: prosody
    state: '{% if
               prosodyconfigrestarts|changed
               or
               sslconf|changed
             %}restarted{% elif
               prosodyconfig|changed
             %}reloaded{%
               else
             %}started{% endif %}'
    enabled: yes
  tags: service

- name: configure users
  prosodyusers:
    jids: '{{ xmpp.jids }}'
  register: prosodyusers
  tags: users
