---

- block:
  - name: copy SSH provisioner script
    copy:
      dest: /var/lib/jenkins/userContent/ssh-provision-jenkins-slave
      src: files/var/lib/jenkins/userContent/ssh-provision-jenkins-slave
      owner: root
      group: root
      mode: 0755
    tags:
    - helpers
    - ssh
    - provision

  - name: copy AWS provisioner script
    copy:
      dest: /var/lib/jenkins/userContent/aws-provision-jenkins-slave
      src: files/var/lib/jenkins/userContent/aws-provision-jenkins-slave
      owner: root
      group: root
      mode: 0755
    tags:
    - helpers
    - aws
    - provision

  - name: create node configuration directories for SSH
    file:
      name: "/var/lib/jenkins/nodes/{{ item.key }}"
      state: directory
      owner: jenkins
      group: jenkins
      mode: 0755
    with_dict: '{{ jenkins.ssh_nodes }}'
    tags:
    - configs
    - jenkins
    - ssh

  - name: create node configuration directories for AWS
    file:
      name: "/var/lib/jenkins/nodes/{{ item.key }}"
      state: directory
      owner: jenkins
      group: jenkins
      mode: 0755
    with_dict: '{{ jenkins.aws_nodes }}'
    tags:
    - configs
    - jenkins
    - ssh

  - name: create node configurations for SSH
    template:
      backup: true
      src: "files/var/lib/jenkins/nodes/template/config.xml.j2"
      dest: "/var/lib/jenkins/nodes/{{ item.key }}/config.xml"
      owner: jenkins
      group: jenkins
      mode: 0644
    vars:
      jenkins_url: '{{ jenkins.url }}'
      agentCommand: /var/lib/jenkins/userContent/ssh-provision-jenkins-slave {{ jenkins_url|quote }} {{ item.value.user|quote }}@{{ item.key|quote }}
    with_dict: '{{ jenkins.ssh_nodes }}'
    tags:
    - configs
    - jenkins
    - ssh
    notify: restart jenkins

  - name: create node configurations for AWS
    template:
      backup: true
      src: "files/var/lib/jenkins/nodes/template/config.xml.j2"
      dest: "/var/lib/jenkins/nodes/{{ item.key }}/config.xml"
      owner: jenkins
      group: jenkins
      mode: 0644
    vars:
      jenkins_url: '{{ jenkins.url }}'
      agentCommand: /var/lib/jenkins/userContent/aws-provision-jenkins-slave {{ jenkins_url|quote }} {{ item.key|quote }} {{ item.value.region|quote }} {{ item.value.ami|quote }} {{ item.value.instance_type|quote }} {{ item.value.security_group|quote }} {{ item.value.subnet_id |quote }} {{ item.value.login_user|quote }} {{ item.value.root_device_size|string|quote }} {{ item.value.ephemeral_device_count|string|quote }}
    with_dict: '{{ jenkins.aws_nodes }}'
    tags:
    - configs
    - jenkins
    - aws
    notify: restart jenkins

  when: qubes.vm_type != 'TemplateVM'
  tags:
  - jenkins-nodes
