#!/bin/bash

export PATH=/usr/sbin:/usr/bin:/sbin:/bin
logger -p user.info -t bogofilter "Marking message as {{ item }}."
output=$(bogofilter -e {% if item == "ham" %}-Sn{% else %}-Ns{% endif %} -M -C 2>&1)
ret=$?
if [ "$ret" != "0" ] ; then
    logger -p user.error -t bogofilter "Error marking message as {{ item }}: $output"
fi
