#!/bin/bash

export PATH=$HOME/bin:/usr/local/bin:$PATH
logger -t bogofilter-reclassify "Marking message as {{ item }}."
output=$(bogofilter -e {% if item == "ham" %}-Sn{% else %}-Ns{% endif %} -M 2>&1)
ret=$?
if [ "$ret" != "0" ] ; then
    logger -t bogofilter-reclassify "Error marking message as {{ item }}: $output"
fi
