#!/bin/bash

export PATH=/usr/sbin:/usr/bin:/sbin:/bin
logger -p user.info -t bogofilter "Classifying message as either spam or ham."
tmp=`mktemp`
trap "rm -f $tmp" EXIT
ret=0
output=$(cat > "$tmp" 2>&1) || ret=$?
if [ "$ret" != "0" ] ; then
    logger -p user.error -t bogofilter "Error buffering incoming message: exited with status $ret, output: $output"
fi
tmp2=`mktemp`
trap "rm -f $tmp $tmp2" EXIT
bogofilter -p -e {% if spam.autoregister_incoming_mail|default(False) %}-u {% endif %}-l -C -I "$tmp" 2> "$tmp2"
ret=$?
if [ "$ret" != "0" ] ; then
    output=`cat "$tmp2"`
    logger -p user.error -t bogofilter "Error classifying message: exited with status $ret, output: $output"
    exit "$ret"
fi
