#!/bin/bash

export PATH=/usr/sbin:/usr/bin:/sbin:/bin
tmp=`mktemp`
trap "rm -f $tmp" EXIT
ret=0
cat > "$tmp" || ret=$?
if [ "$ret" != "0" ] ; then
    logger -p user.error -t bogofilter "Error buffering incoming message: exited with status $ret"
    exit "$ret"
fi

mid=$(grep ^Message-ID: < "$tmp" | head -1 | cut -d '<' -f 2 | cut -d '>' -f 1)
if [ "$mid" == "" ] ; then mid="with no discernible ID" ; fi
logger --id=$$ -p user.info -t bogofilter "Classifying message $mid as either spam or ham."

tmp2=`mktemp`
trap "rm -f $tmp $tmp2" EXIT
bogofilter -p -e {% if spam.autoregister_incoming_mail|default(False) %}-u {% endif %}-l -C -I "$tmp" 2> "$tmp2"
ret=$?
if [ "$ret" != "0" ] ; then
    output=`cat "$tmp2"`
    logger --id=$$ -p user.error -t bogofilter "Error classifying message $mid: exited with status $ret, output: $output"
    exit "$ret"
fi
