- hosts: dom0
  become: true
  vars:
    packages:
    - plasma-workspace
    - plasma-systemsettings
    - plasma-breeze
    - plasma-breeze-qubes
    - kde-settings-plasma
    - plasma-desktop
    - kwin
    - kscreen
    - kde-cli-tools
  tasks:
  - include: tasks/dom0install.yml
  - name: fix PAM settings for kscreensaver so the screen can be unlocked
    shell: |
      cd /etc/pam.d
      diff kscreensaver xscreensaver > /dev/null && {
        echo ALREADY
      } || {
        test -f kscreensaver.bak || cp -f kscreensaver kscreensaver.bak
        cat xscreensaver > kscreensaver
      }
    register: kscreensaverfix
    changed_when: '{{ "ALREADY" not in kscreensaverfix.stdout }}'
  - name: fix color palette
    shell: test -d "$HOME"/.local/share/qubes-kde || { echo YES ; /usr/bin/qubes-generate-color-palette ; }
    become: false
    register: palette
    changed_when: '{{ "YES" in palette.stdout }}'
